### ISSUE TITLE
Configure GitHub Actions for Docker Build and Merge Protection

### ISSUE THREAD

**Issue by dappsar** [P4-Games/ChatterPay#72]
#### **Description**
Set up a GitHub Actions workflow to build the application using Docker for every Pull Request (PR) targeting the `develop` and `main` branches. If the Docker build fails, the merge to these branches should be blocked.

#### **Objective**
- Automate the build process using Docker.
- Prevent Pull Requests from being merged into `develop` and `main` if the build fails.
- Ensure the quality of code going into the critical branches by setting up branch protection rules.

#### **Steps to complete**

1. **Create the GitHub Actions workflow:**
   - Create a new file in the repository under `.github/workflows/docker-build.yml`.
   - Add the following content to the file:

     ```yaml
     name: Docker Build and Test

     on:
       pull_request:
         branches:
           - develop
           - main

     jobs:
       docker-build:
         runs-on: ubuntu-latest

         steps:
           # Check out the repository code
           - name: Checkout repository
             uses: actions/checkout@v2

           # Build the Docker image
           - name: Build Docker image
             run: docker build -t my-app .

           # Optionally, run tests
           # - name: Run tests
           #   run: docker run my-app npm run test
     ```

2. **Set up branch protection rules:**
   - Go to **Settings** > **Branches** in your repository.
   - Under **Branch protection rules**, click **Add rule**.
   - Select `develop` or `main` as the branch to protect.
   - Enable **Require status checks to pass before merging**.
   - Select the workflow (e.g., "Docker Build and Test") as a required status check.
   - Save the changes.

3. **Verify functionality:**
   - Create a test Pull Request targeting `develop` or `main` to ensure that the Docker build runs correctly and fails the PR if the build does not pass.

#### **Expected Outcome**
- The GitHub Actions workflow should run the Docker build on every PR to `develop` and `main`.
- If the build fails, the PR will be blocked from merging.
- Branch protection ensures only successful builds can be merged.
